name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare enviroment
        run: |
            apt-get -y update
            apt-get -y install wget zip unzip

      - name: Build
        run: |
          bash build.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          # Artifact name
          name: Mod
          path: ./out/gaythunder_launcher_mod.zip
